### ISSUE TITLE
[JOSS review] Community guidelines

### ISSUE THREAD

**Issue by rvhonorato** [coleygroup/pyscreener#24]
_Companion of openjournals/joss-reviews/issues/3950_

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

The repository already contains a `CODE_OF_CONDUCT.md` but would also be beneficial to have a `CONTRIBUTING.md` detailing how to contribute to the repository, also there should be issue templates for feature requests/bugs/questions.

**Comment by davidegraff** [comment]
addressed in #32
