### ISSUE TITLE
[JOSS review] Installation Instruction Simplification 

### ISSUE THREAD

**Issue by mikemhenry** [coleygroup/pyscreener#26]
I was able to follow the instructions and run the integration tests :tada: 
The details on installing different docking backends was :ok_hand:  
I do think the installation instructions could be simplified by installing everything from conda-forge:

`conda create -n NAME -c conda-forge python=3.8 pip openbabel openmm rdkit pdbfixer`

Then the extra step to install pdbfixer from source isn't necessary. 

This is a secondary (but related) question:

Are you interested in getting this package on conda-forge? Then end users would only need to (in addtion to installing the backend of thier choice) do:

`conda install -c conda-forge pyscreener`

cc https://github.com/openjournals/joss-reviews/issues/3950

**Comment by davidegraff** [comment]
I think this is a good solution and I'll look to change this.

Re: the second question. I would definitely love to do that and think it could alleviate a decent amount of setup difficulty. I just didn't have time to dedicate to learning conda packaging. If you have any advice, I'd love to hear it!

**Comment by mikemhenry** [comment]
Since this package is on pypi, there is some tooling that will auto-generate what is needed to package this on conda-forge. Since all the dependencies (well not the docking backends but that is okay) are on conda-forge, then it should be pretty easy :tm: Once we wrap up the JOSS review, I would be happy to help to get this on conda-forge

**Comment by davidegraff** [comment]
conda package coming soon™️ ...

thanks so much for the offer to help!
