### ISSUE TITLE
running time

### ISSUE THREAD

**Issue by futianfan** [coleygroup/pyscreener#7]
Dear authors, 

Thanks for your great project! However, when I use pyscreener, the running time for each molecule is 30 seconds in average. Do you have any suggestions for accelerating the process?

**Comment by davidegraff** [comment]
There are a lot of details missing in your question:

- what software are you running?
- what molecules are you running (approximately how many torsion modes + # of atoms)?
- how many cores are you running each docking instance with
- what is your computing setup (# of cores + distributed or local parallelization)?

**Comment by futianfan** [comment]
I use vina. I tried to go over zinc-250k database. I have 14 cpu cores. I observed that pyscreener have implemented parallelization. what's is your setup for "number of workers" and "ncpu"? I set ncpu=10, num_workers=3. do you think there is any problems?

**Comment by davidegraff** [comment]
roughly: `TOTAL_CORES = ncpu * num_workers`. A "worker" is an independent docking process, so if you run each docking process with 4 cores on a 14 core machine, you would probably want only 3 workers. This will use 12 cores of your machine at peak, which while underutilizing the total number of cores on your machine, is better than oversubscribing your cores which will lead to OS scheduling overload. In your example, you've massively oversubscribed and could likely realize a speedup but just decreasing `ncpu` to 4. Alternatively, you could run 7 workers with 2 cores each (`ncpu=2`) to fully utilize all of your cores.

**Comment by futianfan** [comment]
thanks! Will try it.
